'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace VUCEM
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/service/", ConfigurationName:="VUCEM.IReceptor")>  _
    Public Interface IReceptor
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación RecibirCove no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ventanillaunica.gob.mx/RecibirCove", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Persona)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ComprobanteValorElectronicoBase))>  _
        Function RecibirCove(ByVal request As VUCEM.RecibirCoveRequest) As VUCEM.RecibirCoveResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ventanillaunica.gob.mx/RecibirCove", ReplyAction:="*")>  _
        Function RecibirCoveAsync(ByVal request As VUCEM.RecibirCoveRequest) As System.Threading.Tasks.Task(Of VUCEM.RecibirCoveResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación RecibirRelacionFacturasIA no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasIA", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Persona)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ComprobanteValorElectronicoBase))>  _
        Function RecibirRelacionFacturasIA(ByVal request As VUCEM.RecibirRelacionFacturasIARequest) As VUCEM.RecibirRelacionFacturasIAResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasIA", ReplyAction:="*")>  _
        Function RecibirRelacionFacturasIAAsync(ByVal request As VUCEM.RecibirRelacionFacturasIARequest) As System.Threading.Tasks.Task(Of VUCEM.RecibirRelacionFacturasIAResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación RecibirRelacionFacturasNoIA no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasNoIA", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Persona)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ComprobanteValorElectronicoBase))>  _
        Function RecibirRelacionFacturasNoIA(ByVal request As VUCEM.RecibirRelacionFacturasNoIARequest) As VUCEM.RecibirRelacionFacturasNoIAResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasNoIA", ReplyAction:="*")>  _
        Function RecibirRelacionFacturasNoIAAsync(ByVal request As VUCEM.RecibirRelacionFacturasNoIARequest) As System.Threading.Tasks.Task(Of VUCEM.RecibirRelacionFacturasNoIAResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class ComprobanteValorElectronico
        Inherits ComprobanteValorElectronicoBase
        
        Private numeroFacturaOriginalField As String
        
        Private facturaField As FacturaCove
        
        Private emisorField As Emisor
        
        Private destinatarioField As Destinatario
        
        Private mercanciasField() As Mercancia
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property numeroFacturaOriginal() As String
            Get
                Return Me.numeroFacturaOriginalField
            End Get
            Set
                Me.numeroFacturaOriginalField = value
                Me.RaisePropertyChanged("numeroFacturaOriginal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property factura() As FacturaCove
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
                Me.RaisePropertyChanged("factura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property emisor() As Emisor
            Get
                Return Me.emisorField
            End Get
            Set
                Me.emisorField = value
                Me.RaisePropertyChanged("emisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property destinatario() As Destinatario
            Get
                Return Me.destinatarioField
            End Get
            Set
                Me.destinatarioField = value
                Me.RaisePropertyChanged("destinatario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mercancias", Order:=4)>  _
        Public Property mercancias() As Mercancia()
            Get
                Return Me.mercanciasField
            End Get
            Set
                Me.mercanciasField = value
                Me.RaisePropertyChanged("mercancias")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(FacturaNoIA)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(FacturaIA)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class FacturaCove
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private certificadoOrigenField As Integer
        
        Private numeroExportadorAutorizadoField As String
        
        Private subdivisionField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property certificadoOrigen() As Integer
            Get
                Return Me.certificadoOrigenField
            End Get
            Set
                Me.certificadoOrigenField = value
                Me.RaisePropertyChanged("certificadoOrigen")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property numeroExportadorAutorizado() As String
            Get
                Return Me.numeroExportadorAutorizadoField
            End Get
            Set
                Me.numeroExportadorAutorizadoField = value
                Me.RaisePropertyChanged("numeroExportadorAutorizado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property subdivision() As Integer
            Get
                Return Me.subdivisionField
            End Get
            Set
                Me.subdivisionField = value
                Me.RaisePropertyChanged("subdivision")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class Acuse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private numeroDeOperacionField As String
        
        Private horaRecepcionField As Date
        
        Private mensajeInformativoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", Order:=0)>  _
        Public Property numeroDeOperacion() As String
            Get
                Return Me.numeroDeOperacionField
            End Get
            Set
                Me.numeroDeOperacionField = value
                Me.RaisePropertyChanged("numeroDeOperacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property horaRecepcion() As Date
            Get
                Return Me.horaRecepcionField
            End Get
            Set
                Me.horaRecepcionField = value
                Me.RaisePropertyChanged("horaRecepcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property mensajeInformativo() As String
            Get
                Return Me.mensajeInformativoField
            End Get
            Set
                Me.mensajeInformativoField = value
                Me.RaisePropertyChanged("mensajeInformativo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class Domicilio
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private calleField As String
        
        Private numeroExteriorField As String
        
        Private numeroInteriorField As String
        
        Private coloniaField As String
        
        Private localidadField As String
        
        Private municipioField As String
        
        Private entidadFederativaField As String
        
        Private paisField As String
        
        Private codigoPostalField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property calle() As String
            Get
                Return Me.calleField
            End Get
            Set
                Me.calleField = value
                Me.RaisePropertyChanged("calle")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property numeroExterior() As String
            Get
                Return Me.numeroExteriorField
            End Get
            Set
                Me.numeroExteriorField = value
                Me.RaisePropertyChanged("numeroExterior")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property numeroInterior() As String
            Get
                Return Me.numeroInteriorField
            End Get
            Set
                Me.numeroInteriorField = value
                Me.RaisePropertyChanged("numeroInterior")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property colonia() As String
            Get
                Return Me.coloniaField
            End Get
            Set
                Me.coloniaField = value
                Me.RaisePropertyChanged("colonia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set
                Me.localidadField = value
                Me.RaisePropertyChanged("localidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property municipio() As String
            Get
                Return Me.municipioField
            End Get
            Set
                Me.municipioField = value
                Me.RaisePropertyChanged("municipio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property entidadFederativa() As String
            Get
                Return Me.entidadFederativaField
            End Get
            Set
                Me.entidadFederativaField = value
                Me.RaisePropertyChanged("entidadFederativa")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property pais() As String
            Get
                Return Me.paisField
            End Get
            Set
                Me.paisField = value
                Me.RaisePropertyChanged("pais")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property codigoPostal() As String
            Get
                Return Me.codigoPostalField
            End Get
            Set
                Me.codigoPostalField = value
                Me.RaisePropertyChanged("codigoPostal")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Emisor)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Destinatario)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public MustInherit Class Persona
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private tipoIdentificadorField As Integer
        
        Private identificacionField As String
        
        Private apellidoPaternoField As String
        
        Private apellidoMaternoField As String
        
        Private nombreField As String
        
        Private domicilioField As Domicilio
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property tipoIdentificador() As Integer
            Get
                Return Me.tipoIdentificadorField
            End Get
            Set
                Me.tipoIdentificadorField = value
                Me.RaisePropertyChanged("tipoIdentificador")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property identificacion() As String
            Get
                Return Me.identificacionField
            End Get
            Set
                Me.identificacionField = value
                Me.RaisePropertyChanged("identificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property apellidoPaterno() As String
            Get
                Return Me.apellidoPaternoField
            End Get
            Set
                Me.apellidoPaternoField = value
                Me.RaisePropertyChanged("apellidoPaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property apellidoMaterno() As String
            Get
                Return Me.apellidoMaternoField
            End Get
            Set
                Me.apellidoMaternoField = value
                Me.RaisePropertyChanged("apellidoMaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property domicilio() As Domicilio
            Get
                Return Me.domicilioField
            End Get
            Set
                Me.domicilioField = value
                Me.RaisePropertyChanged("domicilio")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class Emisor
        Inherits Persona
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class Destinatario
        Inherits Persona
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class DescripcionMercancia
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private marcaField As String
        
        Private modeloField As String
        
        Private subModeloField As String
        
        Private numeroSerieField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property marca() As String
            Get
                Return Me.marcaField
            End Get
            Set
                Me.marcaField = value
                Me.RaisePropertyChanged("marca")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property modelo() As String
            Get
                Return Me.modeloField
            End Get
            Set
                Me.modeloField = value
                Me.RaisePropertyChanged("modelo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property subModelo() As String
            Get
                Return Me.subModeloField
            End Get
            Set
                Me.subModeloField = value
                Me.RaisePropertyChanged("subModelo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property numeroSerie() As String
            Get
                Return Me.numeroSerieField
            End Get
            Set
                Me.numeroSerieField = value
                Me.RaisePropertyChanged("numeroSerie")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class Mercancia
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private descripcionGenericaField As String
        
        Private claveUnidadMedidaField As String
        
        Private tipoMonedaField As String
        
        Private cantidadField As Decimal
        
        Private valorUnitarioField As Decimal
        
        Private valorTotalField As Decimal
        
        Private valorDolaresField As Decimal
        
        Private descripcionesEspecificasField() As DescripcionMercancia
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property descripcionGenerica() As String
            Get
                Return Me.descripcionGenericaField
            End Get
            Set
                Me.descripcionGenericaField = value
                Me.RaisePropertyChanged("descripcionGenerica")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property claveUnidadMedida() As String
            Get
                Return Me.claveUnidadMedidaField
            End Get
            Set
                Me.claveUnidadMedidaField = value
                Me.RaisePropertyChanged("claveUnidadMedida")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property tipoMoneda() As String
            Get
                Return Me.tipoMonedaField
            End Get
            Set
                Me.tipoMonedaField = value
                Me.RaisePropertyChanged("tipoMoneda")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
                Me.RaisePropertyChanged("cantidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property valorUnitario() As Decimal
            Get
                Return Me.valorUnitarioField
            End Get
            Set
                Me.valorUnitarioField = value
                Me.RaisePropertyChanged("valorUnitario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property valorTotal() As Decimal
            Get
                Return Me.valorTotalField
            End Get
            Set
                Me.valorTotalField = value
                Me.RaisePropertyChanged("valorTotal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property valorDolares() As Decimal
            Get
                Return Me.valorDolaresField
            End Get
            Set
                Me.valorDolaresField = value
                Me.RaisePropertyChanged("valorDolares")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("descripcionesEspecificas", Order:=7)>  _
        Public Property descripcionesEspecificas() As DescripcionMercancia()
            Get
                Return Me.descripcionesEspecificasField
            End Get
            Set
                Me.descripcionesEspecificasField = value
                Me.RaisePropertyChanged("descripcionesEspecificas")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class FirmaElectronica
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private certificadoField() As Byte
        
        Private cadenaOriginalField As String
        
        Private firmaField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=0)>  _
        Public Property certificado() As Byte()
            Get
                Return Me.certificadoField
            End Get
            Set
                Me.certificadoField = value
                Me.RaisePropertyChanged("certificado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property cadenaOriginal() As String
            Get
                Return Me.cadenaOriginalField
            End Get
            Set
                Me.cadenaOriginalField = value
                Me.RaisePropertyChanged("cadenaOriginal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=2)>  _
        Public Property firma() As Byte()
            Get
                Return Me.firmaField
            End Get
            Set
                Me.firmaField = value
                Me.RaisePropertyChanged("firma")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ComprobanteValorElectronicoNoIA)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ComprobanteValorElectronicoIA)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ComprobanteValorElectronico)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public MustInherit Class ComprobanteValorElectronicoBase
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private edocumentField As String
        
        Private tipoOperacionField As TipoOperacion
        
        Private patenteAduanalField() As String
        
        Private fechaExpedicionField As Date
        
        Private observacionesField As String
        
        Private rfcConsultaField() As String
        
        Private tipoFiguraField As Integer
        
        Private correoElectronicoField As String
        
        Private firmaElectronicaField As FirmaElectronica
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("e-document", IsNullable:=true, Order:=0)>  _
        Public Property edocument() As String
            Get
                Return Me.edocumentField
            End Get
            Set
                Me.edocumentField = value
                Me.RaisePropertyChanged("edocument")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property tipoOperacion() As TipoOperacion
            Get
                Return Me.tipoOperacionField
            End Get
            Set
                Me.tipoOperacionField = value
                Me.RaisePropertyChanged("tipoOperacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("patenteAduanal", Order:=2)>  _
        Public Property patenteAduanal() As String()
            Get
                Return Me.patenteAduanalField
            End Get
            Set
                Me.patenteAduanalField = value
                Me.RaisePropertyChanged("patenteAduanal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=3)>  _
        Public Property fechaExpedicion() As Date
            Get
                Return Me.fechaExpedicionField
            End Get
            Set
                Me.fechaExpedicionField = value
                Me.RaisePropertyChanged("fechaExpedicion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property observaciones() As String
            Get
                Return Me.observacionesField
            End Get
            Set
                Me.observacionesField = value
                Me.RaisePropertyChanged("observaciones")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("rfcConsulta", Order:=5)>  _
        Public Property rfcConsulta() As String()
            Get
                Return Me.rfcConsultaField
            End Get
            Set
                Me.rfcConsultaField = value
                Me.RaisePropertyChanged("rfcConsulta")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property tipoFigura() As Integer
            Get
                Return Me.tipoFiguraField
            End Get
            Set
                Me.tipoFiguraField = value
                Me.RaisePropertyChanged("tipoFigura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property correoElectronico() As String
            Get
                Return Me.correoElectronicoField
            End Get
            Set
                Me.correoElectronicoField = value
                Me.RaisePropertyChanged("correoElectronico")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property firmaElectronica() As FirmaElectronica
            Get
                Return Me.firmaElectronicaField
            End Get
            Set
                Me.firmaElectronicaField = value
                Me.RaisePropertyChanged("firmaElectronica")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Public Enum TipoOperacion
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("TOCE.IMP")>  _
        TOCEIMP
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("TOCE.EXP")>  _
        TOCEEXP
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class ComprobanteValorElectronicoNoIA
        Inherits ComprobanteValorElectronicoBase
        
        Private numeroRelacionFacturasField As String
        
        Private facturasField() As FacturaNoIA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property numeroRelacionFacturas() As String
            Get
                Return Me.numeroRelacionFacturasField
            End Get
            Set
                Me.numeroRelacionFacturasField = value
                Me.RaisePropertyChanged("numeroRelacionFacturas")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("facturas", Order:=1)>  _
        Public Property facturas() As FacturaNoIA()
            Get
                Return Me.facturasField
            End Get
            Set
                Me.facturasField = value
                Me.RaisePropertyChanged("facturas")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class FacturaNoIA
        Inherits FacturaCove
        
        Private numeroFacturaField As String
        
        Private emisorField As Emisor
        
        Private destinatarioField As Destinatario
        
        Private mercanciasField() As Mercancia
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property numeroFactura() As String
            Get
                Return Me.numeroFacturaField
            End Get
            Set
                Me.numeroFacturaField = value
                Me.RaisePropertyChanged("numeroFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property emisor() As Emisor
            Get
                Return Me.emisorField
            End Get
            Set
                Me.emisorField = value
                Me.RaisePropertyChanged("emisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property destinatario() As Destinatario
            Get
                Return Me.destinatarioField
            End Get
            Set
                Me.destinatarioField = value
                Me.RaisePropertyChanged("destinatario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mercancias", Order:=3)>  _
        Public Property mercancias() As Mercancia()
            Get
                Return Me.mercanciasField
            End Get
            Set
                Me.mercanciasField = value
                Me.RaisePropertyChanged("mercancias")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class ComprobanteValorElectronicoIA
        Inherits ComprobanteValorElectronicoBase
        
        Private numeroRelacionFacturasField As String
        
        Private emisorField As Emisor
        
        Private destinatarioField As Destinatario
        
        Private facturasField() As FacturaIA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property numeroRelacionFacturas() As String
            Get
                Return Me.numeroRelacionFacturasField
            End Get
            Set
                Me.numeroRelacionFacturasField = value
                Me.RaisePropertyChanged("numeroRelacionFacturas")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property emisor() As Emisor
            Get
                Return Me.emisorField
            End Get
            Set
                Me.emisorField = value
                Me.RaisePropertyChanged("emisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property destinatario() As Destinatario
            Get
                Return Me.destinatarioField
            End Get
            Set
                Me.destinatarioField = value
                Me.RaisePropertyChanged("destinatario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("facturas", Order:=3)>  _
        Public Property facturas() As FacturaIA()
            Get
                Return Me.facturasField
            End Get
            Set
                Me.facturasField = value
                Me.RaisePropertyChanged("facturas")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")>  _
    Partial Public Class FacturaIA
        Inherits FacturaCove
        
        Private numeroFacturaField As String
        
        Private mercanciasField() As Mercancia
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property numeroFactura() As String
            Get
                Return Me.numeroFacturaField
            End Get
            Set
                Me.numeroFacturaField = value
                Me.RaisePropertyChanged("numeroFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mercancias", Order:=1)>  _
        Public Property mercancias() As Mercancia()
            Get
                Return Me.mercanciasField
            End Get
            Set
                Me.mercanciasField = value
                Me.RaisePropertyChanged("mercancias")
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirCoveRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable:=false)>  _
        Public solicitarRecibirCoveServicio() As VUCEM.ComprobanteValorElectronico
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal solicitarRecibirCoveServicio() As VUCEM.ComprobanteValorElectronico)
            MyBase.New
            Me.solicitarRecibirCoveServicio = solicitarRecibirCoveServicio
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirCoveResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order:=0)>  _
        Public solicitarRecibirCoveServicioResponse As VUCEM.Acuse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal solicitarRecibirCoveServicioResponse As VUCEM.Acuse)
            MyBase.New
            Me.solicitarRecibirCoveServicioResponse = solicitarRecibirCoveServicioResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirRelacionFacturasIARequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable:=false)>  _
        Public solicitarRecibirRelacionFacturasIAServicio() As VUCEM.ComprobanteValorElectronicoIA
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal solicitarRecibirRelacionFacturasIAServicio() As VUCEM.ComprobanteValorElectronicoIA)
            MyBase.New
            Me.solicitarRecibirRelacionFacturasIAServicio = solicitarRecibirRelacionFacturasIAServicio
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirRelacionFacturasIAResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order:=0)>  _
        Public solicitarRecibirRelacionFacturasIAServicioResponse As VUCEM.Acuse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal solicitarRecibirRelacionFacturasIAServicioResponse As VUCEM.Acuse)
            MyBase.New
            Me.solicitarRecibirRelacionFacturasIAServicioResponse = solicitarRecibirRelacionFacturasIAServicioResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirRelacionFacturasNoIARequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable:=false)>  _
        Public solicitarRecibirRelacionFacturasNoIAServicio() As VUCEM.ComprobanteValorElectronicoNoIA
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal solicitarRecibirRelacionFacturasNoIAServicio() As VUCEM.ComprobanteValorElectronicoNoIA)
            MyBase.New
            Me.solicitarRecibirRelacionFacturasNoIAServicio = solicitarRecibirRelacionFacturasNoIAServicio
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirRelacionFacturasNoIAResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order:=0)>  _
        Public solicitarRecibirRelacionFacturasNoIAServicioResponse As VUCEM.Acuse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal solicitarRecibirRelacionFacturasNoIAServicioResponse As VUCEM.Acuse)
            MyBase.New
            Me.solicitarRecibirRelacionFacturasNoIAServicioResponse = solicitarRecibirRelacionFacturasNoIAServicioResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IReceptorChannel
        Inherits VUCEM.IReceptor, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ReceptorClient
        Inherits System.ServiceModel.ClientBase(Of VUCEM.IReceptor)
        Implements VUCEM.IReceptor
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VUCEM_IReceptor_RecibirCove(ByVal request As VUCEM.RecibirCoveRequest) As VUCEM.RecibirCoveResponse Implements VUCEM.IReceptor.RecibirCove
            Return MyBase.Channel.RecibirCove(request)
        End Function
        
        Public Function RecibirCove(ByVal solicitarRecibirCoveServicio() As VUCEM.ComprobanteValorElectronico) As VUCEM.Acuse
            Dim inValue As VUCEM.RecibirCoveRequest = New VUCEM.RecibirCoveRequest()
            inValue.solicitarRecibirCoveServicio = solicitarRecibirCoveServicio
            Dim retVal As VUCEM.RecibirCoveResponse = CType(Me,VUCEM.IReceptor).RecibirCove(inValue)
            Return retVal.solicitarRecibirCoveServicioResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VUCEM_IReceptor_RecibirCoveAsync(ByVal request As VUCEM.RecibirCoveRequest) As System.Threading.Tasks.Task(Of VUCEM.RecibirCoveResponse) Implements VUCEM.IReceptor.RecibirCoveAsync
            Return MyBase.Channel.RecibirCoveAsync(request)
        End Function
        
        Public Function RecibirCoveAsync(ByVal solicitarRecibirCoveServicio() As VUCEM.ComprobanteValorElectronico) As System.Threading.Tasks.Task(Of VUCEM.RecibirCoveResponse)
            Dim inValue As VUCEM.RecibirCoveRequest = New VUCEM.RecibirCoveRequest()
            inValue.solicitarRecibirCoveServicio = solicitarRecibirCoveServicio
            Return CType(Me,VUCEM.IReceptor).RecibirCoveAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VUCEM_IReceptor_RecibirRelacionFacturasIA(ByVal request As VUCEM.RecibirRelacionFacturasIARequest) As VUCEM.RecibirRelacionFacturasIAResponse Implements VUCEM.IReceptor.RecibirRelacionFacturasIA
            Return MyBase.Channel.RecibirRelacionFacturasIA(request)
        End Function
        
        Public Function RecibirRelacionFacturasIA(ByVal solicitarRecibirRelacionFacturasIAServicio() As VUCEM.ComprobanteValorElectronicoIA) As VUCEM.Acuse
            Dim inValue As VUCEM.RecibirRelacionFacturasIARequest = New VUCEM.RecibirRelacionFacturasIARequest()
            inValue.solicitarRecibirRelacionFacturasIAServicio = solicitarRecibirRelacionFacturasIAServicio
            Dim retVal As VUCEM.RecibirRelacionFacturasIAResponse = CType(Me,VUCEM.IReceptor).RecibirRelacionFacturasIA(inValue)
            Return retVal.solicitarRecibirRelacionFacturasIAServicioResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VUCEM_IReceptor_RecibirRelacionFacturasIAAsync(ByVal request As VUCEM.RecibirRelacionFacturasIARequest) As System.Threading.Tasks.Task(Of VUCEM.RecibirRelacionFacturasIAResponse) Implements VUCEM.IReceptor.RecibirRelacionFacturasIAAsync
            Return MyBase.Channel.RecibirRelacionFacturasIAAsync(request)
        End Function
        
        Public Function RecibirRelacionFacturasIAAsync(ByVal solicitarRecibirRelacionFacturasIAServicio() As VUCEM.ComprobanteValorElectronicoIA) As System.Threading.Tasks.Task(Of VUCEM.RecibirRelacionFacturasIAResponse)
            Dim inValue As VUCEM.RecibirRelacionFacturasIARequest = New VUCEM.RecibirRelacionFacturasIARequest()
            inValue.solicitarRecibirRelacionFacturasIAServicio = solicitarRecibirRelacionFacturasIAServicio
            Return CType(Me,VUCEM.IReceptor).RecibirRelacionFacturasIAAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VUCEM_IReceptor_RecibirRelacionFacturasNoIA(ByVal request As VUCEM.RecibirRelacionFacturasNoIARequest) As VUCEM.RecibirRelacionFacturasNoIAResponse Implements VUCEM.IReceptor.RecibirRelacionFacturasNoIA
            Return MyBase.Channel.RecibirRelacionFacturasNoIA(request)
        End Function
        
        Public Function RecibirRelacionFacturasNoIA(ByVal solicitarRecibirRelacionFacturasNoIAServicio() As VUCEM.ComprobanteValorElectronicoNoIA) As VUCEM.Acuse
            Dim inValue As VUCEM.RecibirRelacionFacturasNoIARequest = New VUCEM.RecibirRelacionFacturasNoIARequest()
            inValue.solicitarRecibirRelacionFacturasNoIAServicio = solicitarRecibirRelacionFacturasNoIAServicio
            Dim retVal As VUCEM.RecibirRelacionFacturasNoIAResponse = CType(Me,VUCEM.IReceptor).RecibirRelacionFacturasNoIA(inValue)
            Return retVal.solicitarRecibirRelacionFacturasNoIAServicioResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VUCEM_IReceptor_RecibirRelacionFacturasNoIAAsync(ByVal request As VUCEM.RecibirRelacionFacturasNoIARequest) As System.Threading.Tasks.Task(Of VUCEM.RecibirRelacionFacturasNoIAResponse) Implements VUCEM.IReceptor.RecibirRelacionFacturasNoIAAsync
            Return MyBase.Channel.RecibirRelacionFacturasNoIAAsync(request)
        End Function
        
        Public Function RecibirRelacionFacturasNoIAAsync(ByVal solicitarRecibirRelacionFacturasNoIAServicio() As VUCEM.ComprobanteValorElectronicoNoIA) As System.Threading.Tasks.Task(Of VUCEM.RecibirRelacionFacturasNoIAResponse)
            Dim inValue As VUCEM.RecibirRelacionFacturasNoIARequest = New VUCEM.RecibirRelacionFacturasNoIARequest()
            inValue.solicitarRecibirRelacionFacturasNoIAServicio = solicitarRecibirRelacionFacturasNoIAServicio
            Return CType(Me,VUCEM.IReceptor).RecibirRelacionFacturasNoIAAsync(inValue)
        End Function
    End Class
End Namespace
